name: Tests Workflow
on: push

jobs:
  before_job: # 最初に実行
    runs-on: ubuntu-latest
    steps:
        - run: echo "RESULT=HELLO" >> "${GITHUB_ENV}"
        - run: echo "${RESULT}"
  after_job:
    runs-on: ubuntu-latest
    needs: before_job # 依存関係のジョブを定義
    steps:
        - run: echo $RESULT
