name: Tests Workflow
on: push

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
    - name: Set state
      id: set-state
      run: |
        echo "MY_STATE=some_value" >> $GITHUB_STATE

    - name: Get MY_STATE
      run: |
        echo "The state is ${{ steps.set-state.MY_STATE }}"