name: Tests Workflow
on: push

jobs:
  job1: # 最初に実行
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "job1"
  job2: # 最初に実行
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "job2"
  job3: # job1とjob2が終了した後に実行
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:
      - run: sleep 10 && echo "job3"