name: Tests Workflow
on: push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'main')}}

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
    - name: sleep
      run: |
        sleep 30