name: Tests Workflow
on: push

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
    - name: Set state
      id: set-state
      run: |
        echo "MY_STATE=some_value" >> $GITHUB_STATE
      outputs:
        result: ${{ steps.set-state.outputs.MY_STATE }}

    - name: Get state
      run: |
        echo "The state is ${{ steps.set-state.outputs.result }}"