name: Tests Workflow
on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: sleep && echo "job1"
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: sleep && echo "job2"
  job3:
    runs-on: ubuntu-latest
    steps:
      - run: sleep && echo "job3"